import { pmsBaseProvisioningSchemaVersion, type HotelProfile, type PmsBaseProvisioningSpec } from './schema.js';
import { smallHotelProfileFixture } from './profile.js';
import {
  housekeepingTasksTable,
  inventoryCalendarTable,
  maintenanceTicketsTable,
  operationLogsTable,
  operationRequestsTable,
  projectionStatusTable,
  reservationsTable,
  roomLedgerTable,
  staysTable,
} from './tables.js';

export function createSmallHotelPmsBaseProvisioningSpec(profile: HotelProfile = smallHotelProfileFixture): PmsBaseProvisioningSpec {
  return {
    schemaVersion: pmsBaseProvisioningSchemaVersion,
    base: {
      logicalName: profile.propertyKey,
      displayName: profile.baseDisplayName,
      timeZone: profile.timeZone,
    },
    profile,
    proof: {
      proofRoomNumbers: profile.proofRoomNumbers,
      requiredWorkflows: profile.enabledWorkflows,
    },
    tables: [
      roomLedgerTable(profile),
      operationRequestsTable(profile),
      housekeepingTasksTable(),
      maintenanceTicketsTable(),
      reservationsTable(),
      staysTable(),
      operationLogsTable(),
      inventoryCalendarTable(),
      projectionStatusTable(),
    ],
    forms: [
      {
        logicalName: 'operation-request-intake',
        displayName: 'PMS操作请求表单',
        tableLogicalName: 'OperationRequests',
        description: '受控 PMS 操作请求入口；确认类操作仍必须来自卡片回调。',
      },
    ],
    adapterRegistryBindings: {
      pmsBaseProjection: {
        version: 1,
        targetPolicy: {
          generatedTargetsAreLocalOnly: true,
        },
        bindings: {
          roomLedger: {
            tableLogicalName: 'RoomLedger',
            fieldMap: {
              backendId: '后端ID',
              roomNumber: '房号',
              roomType: '房型',
              occupancyStatus: '入住状态',
              cleaningStatus: '清洁状态',
              sellableStatus: '可售状态',
              roomCode: '房态码',
              currentReservationCode: '当前预订',
              maintenanceNote: '维修备注',
              housekeepingTaskStatus: '保洁任务状态',
              lastOperator: '最后操作人',
              lastReason: '最后原因',
              lastUpdatedAt: '更新时间',
            },
            requiredFields: [
              'roomNumber',
              'roomType',
              'occupancyStatus',
              'cleaningStatus',
              'sellableStatus',
              'roomCode',
              'lastOperator',
              'lastReason',
              'lastUpdatedAt',
            ],
            updateAllowedFields: [
              'backendId',
              'roomType',
              'occupancyStatus',
              'cleaningStatus',
              'sellableStatus',
              'roomCode',
              'currentReservationCode',
              'maintenanceNote',
              'housekeepingTaskStatus',
              'lastOperator',
              'lastReason',
              'lastUpdatedAt',
            ],
          },
          operationRequests: {
            tableLogicalName: 'OperationRequests',
            fieldMap: {
              backendId: '后端ID',
              clientToken: '请求令牌',
              action: '操作类型',
              status: '操作状态',
              roomNumber: '房号',
              operator: '操作人',
              reason: '原因',
              requestedAt: '请求时间',
              payloadJSON: '请求JSON',
              resultJSON: '结果JSON',
              schemaVersion: '版本',
            },
            requiredFields: ['clientToken', 'action', 'status', 'roomNumber', 'operator', 'reason', 'requestedAt', 'schemaVersion'],
            updateAllowedFields: ['backendId', 'status', 'resultJSON', 'schemaVersion'],
          },
          housekeepingTasks: {
            tableLogicalName: 'HousekeepingTasks',
            fieldMap: {
              backendId: '后端ID',
              taskId: '任务ID',
              roomNumber: '房号',
              relatedRoom: '关联房间',
              kind: '任务类型',
              status: '任务状态',
              reason: '原因',
              correlationId: '关联ID',
              createdAt: '创建时间',
              completedAt: '完成时间',
              schemaVersion: '版本',
            },
            requiredFields: ['taskId', 'roomNumber', 'kind', 'status', 'reason', 'correlationId', 'createdAt', 'schemaVersion'],
            updateAllowedFields: ['backendId', 'relatedRoom', 'status', 'reason', 'completedAt', 'schemaVersion'],
          },
          maintenanceTickets: {
            tableLogicalName: 'MaintenanceTickets',
            fieldMap: {
              backendId: '后端ID',
              ticketId: '工单ID',
              roomNumber: '房号',
              relatedRoom: '关联房间',
              status: '工单状态',
              severity: '严重级别',
              stopSellRequested: '是否停售',
              reason: '维修备注',
              correlationId: '关联ID',
              createdAt: '创建时间',
              resolvedAt: '完成时间',
              schemaVersion: '版本',
            },
            requiredFields: ['ticketId', 'roomNumber', 'status', 'severity', 'stopSellRequested', 'reason', 'correlationId', 'createdAt', 'schemaVersion'],
            updateAllowedFields: ['backendId', 'relatedRoom', 'status', 'resolvedAt', 'schemaVersion'],
          },
          reservations: {
            tableLogicalName: 'Reservations',
            fieldMap: {
              backendId: '后端ID',
              reservationCode: '预订号',
              roomNumber: '房号',
              relatedRoom: '关联房间',
              guestLabel: '客人',
              arrivalDate: '到店日期',
              departureDate: '离店日期',
              status: '预订状态',
              schemaVersion: '版本',
            },
            requiredFields: ['reservationCode', 'guestLabel', 'arrivalDate', 'departureDate', 'status', 'schemaVersion'],
            updateAllowedFields: ['backendId', 'roomNumber', 'relatedRoom', 'guestLabel', 'arrivalDate', 'departureDate', 'status', 'schemaVersion'],
          },
          stays: {
            tableLogicalName: 'Stays',
            fieldMap: {
              backendId: '后端ID',
              reservationCode: '预订号',
              roomNumber: '房号',
              relatedRoom: '关联房间',
              status: '入住状态',
              checkedInAt: '入住时间',
              checkedOutAt: '离店时间',
              schemaVersion: '版本',
            },
            requiredFields: ['backendId', 'reservationCode', 'roomNumber', 'status', 'checkedInAt', 'schemaVersion'],
            updateAllowedFields: ['reservationCode', 'roomNumber', 'relatedRoom', 'status', 'checkedInAt', 'checkedOutAt', 'schemaVersion'],
          },
          inventoryCalendar: {
            tableLogicalName: 'InventoryCalendar',
            fieldMap: {
              backendId: '后端ID',
              intervalKey: '库存区间键',
              propertyId: '门店ID',
              roomId: '房间ID',
              roomNumber: '房号',
              relatedRoom: '关联房间',
              roomTypeId: '房型ID',
              roomType: '房型',
              startDate: '开始日期',
              endDate: '结束日期',
              calendarKind: '日历状态',
              sellableStatus: '可售状态',
              title: '标题',
              sourceRefsJSON: '来源JSON',
              projectionStatus: '投影状态',
              prunedAt: '剪枝时间',
              updatedAt: '更新时间',
              schemaVersion: '版本',
            },
            requiredFields: [
              'intervalKey',
              'propertyId',
              'roomId',
              'roomNumber',
              'startDate',
              'endDate',
              'calendarKind',
              'sellableStatus',
              'title',
              'sourceRefsJSON',
              'projectionStatus',
              'updatedAt',
              'schemaVersion',
            ],
            updateAllowedFields: [
              'backendId',
              'roomNumber',
              'relatedRoom',
              'roomTypeId',
              'roomType',
              'startDate',
              'endDate',
              'calendarKind',
              'sellableStatus',
              'title',
              'sourceRefsJSON',
              'projectionStatus',
              'prunedAt',
              'updatedAt',
              'schemaVersion',
            ],
          },
          operationLogs: {
            tableLogicalName: 'OperationLogs',
            fieldMap: {
              backendId: '后端ID',
              auditId: '审计ID',
              commandType: '操作类型',
              roomNumber: '房号',
              relatedRoom: '关联房间',
              relatedOperationRequest: '关联操作请求',
              actor: '操作人',
              source: '来源',
              reason: '原因',
              idempotencyKey: '幂等键',
              correlationId: '关联ID',
              occurredAt: '发生时间',
              domainEventTypes: '领域事件',
              payloadJSON: '载荷JSON',
              schemaVersion: '版本',
            },
            requiredFields: [
              'auditId',
              'commandType',
              'roomNumber',
              'actor',
              'source',
              'reason',
              'idempotencyKey',
              'correlationId',
              'occurredAt',
              'domainEventTypes',
              'schemaVersion',
            ],
            updateAllowedFields: [],
          },
          projectionStatus: {
            tableLogicalName: 'ProjectionStatus',
            fieldMap: {
              backendId: '后端ID',
              projectionName: '投影名称',
              aggregateKey: '聚合键',
              status: '状态',
              attemptCount: '尝试次数',
              lastProjectedAt: '最近投影时间',
              lastErrorSummary: '错误摘要',
              updatedAt: '更新时间',
              schemaVersion: '版本',
            },
            requiredFields: ['backendId', 'projectionName', 'aggregateKey', 'status', 'attemptCount', 'updatedAt', 'schemaVersion'],
            updateAllowedFields: ['projectionName', 'aggregateKey', 'status', 'attemptCount', 'lastProjectedAt', 'lastErrorSummary', 'updatedAt', 'schemaVersion'],
          },
        },
      },
    },
    validationGates: [
      'required_tables',
      'required_fields',
      'proof_rooms_seeded',
      'operation_request_upsert_policy',
      'hidden_canonical_id_fields',
      'symbolic_linked_record_fields',
      'projection_status_schema',
      'no_tracked_target_values',
    ],
  };
}
