import {
  apiPackageName,
  pmsAvailabilitySearchOperation,
  pmsCapabilityManifestOperation,
  pmsCheckInOperation,
  pmsCheckOutOperation,
  pmsDashboardOperation,
  pmsGetRoomOperation,
  pmsHousekeepingDoneOperation,
  pmsHousekeepingInspectionOperation,
  pmsHousekeepingReworkOperation,
  pmsInventoryIntervalsOperation,
  pmsInventorySummaryOperation,
  pmsMaintenanceDoneOperation,
  pmsOperationRequestCreateOperation,
  pmsOperationRequestGetOperation,
  pmsOperationRequestListOperation,
  pmsOperationRequestUpdateOperation,
  pmsPendingActionCancelOperation,
  pmsPendingActionConfirmOperation,
  pmsPendingActionStatusOperation,
  pmsReportMaintenanceOperation,
  pmsReservationDraftCancelOperation,
  pmsReservationDraftCreateOperation,
  pmsReservationDraftUpdateOperation,
  pmsReservationGetOperation,
  pmsReservationGroupDraftCancelOperation,
  pmsReservationGroupDraftCreateOperation,
  pmsReservationGroupDraftUpdateOperation,
  pmsReservationGroupPrepareConfirmOperation,
  pmsReservationGroupQuoteOperation,
  pmsReservationPrepareConfirmOperation,
  pmsReservationQuoteOperation,
  pmsRestoreSellableOperation,
  pmsRoomReservationContextOperation,
  pmsTodayArrivalsOperation,
  pmsTodayDeparturesOperation,
} from './operations.js';

export function describeApiContractBoundary() {
  return {
    packageName: apiPackageName,
    operation: pmsCheckOutOperation,
    operations: [
      pmsCheckInOperation,
      pmsCheckOutOperation,
      pmsHousekeepingDoneOperation,
      pmsHousekeepingInspectionOperation,
      pmsHousekeepingReworkOperation,
      pmsReportMaintenanceOperation,
      pmsMaintenanceDoneOperation,
      pmsRestoreSellableOperation,
      pmsGetRoomOperation,
      pmsDashboardOperation,
      pmsReservationGetOperation,
      pmsTodayArrivalsOperation,
      pmsTodayDeparturesOperation,
      pmsRoomReservationContextOperation,
      pmsInventoryIntervalsOperation,
      pmsInventorySummaryOperation,
      pmsAvailabilitySearchOperation,
      pmsReservationDraftCreateOperation,
      pmsReservationDraftUpdateOperation,
      pmsReservationQuoteOperation,
      pmsReservationPrepareConfirmOperation,
      pmsReservationDraftCancelOperation,
      pmsReservationGroupDraftCreateOperation,
      pmsReservationGroupDraftUpdateOperation,
      pmsReservationGroupQuoteOperation,
      pmsReservationGroupPrepareConfirmOperation,
      pmsReservationGroupDraftCancelOperation,
      pmsPendingActionStatusOperation,
      pmsPendingActionConfirmOperation,
      pmsPendingActionCancelOperation,
      pmsOperationRequestCreateOperation,
      pmsOperationRequestGetOperation,
      pmsOperationRequestListOperation,
      pmsOperationRequestUpdateOperation,
      pmsCapabilityManifestOperation,
    ] as const,
    importsCoreResult: true,
    exposesLocalHandler: true,
    supportedModes: ['dryRun', 'confirm'] as const,
  };
}
