import type { CommandExecutionMode, DomainError } from '@pms-platform/contracts';

export type ApiBoundaryErrorCode =
  | 'IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_FINGERPRINT'
  | 'RESERVATION_DRAFT_TOKEN_REUSED_WITH_DIFFERENT_FINGERPRINT'
  | 'RESERVATION_DRAFT_NOT_FOUND'
  | 'RESERVATION_DRAFT_MISSING_REQUIRED_SLOTS'
  | 'RESERVATION_DRAFT_NOT_ACTIVE'
  | 'RESERVATION_DRAFT_EXPIRED'
  | 'RESERVATION_DRAFT_QUOTE_REQUIRED'
  | 'RESERVATION_DRAFT_QUOTE_MISMATCH'
  | 'RESERVATION_DRAFT_WORKFLOW_NOT_IMPLEMENTED'
  | 'RESERVATION_QUOTE_PRICING_UNSUPPORTED'
  | 'RESERVATION_GROUP_DRAFT_TOKEN_REUSED_WITH_DIFFERENT_FINGERPRINT'
  | 'RESERVATION_GROUP_DRAFT_NOT_FOUND'
  | 'RESERVATION_GROUP_DRAFT_MISSING_REQUIRED_SLOTS'
  | 'RESERVATION_GROUP_DRAFT_NOT_ACTIVE'
  | 'RESERVATION_GROUP_DRAFT_EXPIRED'
  | 'RESERVATION_GROUP_DRAFT_QUOTE_REQUIRED'
  | 'RESERVATION_GROUP_DRAFT_QUOTE_MISMATCH'
  | 'RESERVATION_GROUP_DRAFT_WORKFLOW_NOT_IMPLEMENTED'
  | 'RESERVATION_GROUP_QUOTE_PRICING_UNSUPPORTED'
  | 'RESERVATION_CANCEL_TOKEN_REUSED_WITH_DIFFERENT_FINGERPRINT'
  | 'RESERVATION_CANCEL_NOT_FOUND'
  | 'RESERVATION_CANCEL_NOT_ACTIVE'
  | 'RESERVATION_CANCEL_WORKFLOW_NOT_IMPLEMENTED'
  | 'OPERATION_REQUEST_TOKEN_REUSED_WITH_DIFFERENT_FINGERPRINT'
  | 'OPERATION_REQUEST_UNSUPPORTED_ACTION'
  | 'OPERATION_REQUEST_UNSUPPORTED_SOURCE'
  | 'OPERATION_REQUEST_NOT_FOUND'
  | 'OPERATION_REQUEST_INVALID_STATUS'
  | 'PENDING_ACTION_TOKEN_REUSED_WITH_DIFFERENT_FINGERPRINT'
  | 'PENDING_ACTION_NOT_FOUND'
  | 'PENDING_ACTION_CARD_PAYLOAD_MISMATCH'
  | 'PENDING_ACTION_NOT_ACTIVE'
  | 'PENDING_ACTION_EXPIRED'
  | 'RESERVATION_ROOM_UNAVAILABLE';
export type ApiErrorCode = DomainError['code'] | ApiBoundaryErrorCode;

export interface ApiError {
  readonly code: ApiErrorCode;
  readonly message: string;
  readonly field?: string;
}

export interface StableErrorPassthrough {
  readonly ok: false;
  readonly mode: CommandExecutionMode | 'unsupported';
  readonly errors: readonly ApiError[];
}
